### ISSUE TITLE
`convert()` would be nicer if it picked up the format from `DESCRIPTION`

### ISSUE THREAD

**Issue by danielinteractive** [dgkf/roxytypes#7]
Currently, in my test case on `jmpost` repo I need to manually give the "old" manual format as argument to `convert()`, even though I specified it already in `Config/roxytypes: list(format = "(`{type}`)\\cr {description}")`. It would be nicer from `convert()` if it picked up the default "old" manual = target format from `DESCRIPTION` .

**Comment by dgkf** [comment]
Great idea! I hadn't even thought of that as a workflow. I always considered `Config/roxytypes`' `format` as an "output" and the convert argument as an "input", but if you want a 1-to-1 conversion, it makes sense that they would be one-in-the-same.

**Comment by dgkf** [comment]
Just FYI - Have reproduced it locally and will try to knock out a fix.
