### ISSUE TITLE
`convert()` duplicates the `#'` in front of the roxygen lines

### ISSUE THREAD

**Issue by danielinteractive** [dgkf/roxytypes#8]
When applying ``convert("(`{type}`)\\cr {description}")`` in `jmpost` I get as changes:
![image](https://github.com/openpharma/roxytypes/assets/1071227/c603d572-aacd-4cc1-9b9d-f5bcde10a9a6)
so although it does not preview it like that, the preview being:
![image](https://github.com/openpharma/roxytypes/assets/1071227/11deff23-a9e0-4e80-b46f-a8b6af576e83)
`convert()` does duplicate the `#'` in front of the roxygen lines.

**Comment by dgkf** [comment]
Interesting! I've converted a couple packages as tests and not seen this before. I'll have to investigate.

As a minor aside, it also looks like the CLI line number gutter is using the "dark theme" background, but that's less critical here.

@danielinteractive - Can you share the `roxygen2` version you're using?

**Comment by danielinteractive** [comment]
thanks @dgkf , `roxygen2` is at 7.2.3

**Comment by danielinteractive** [comment]
You can see this e.g. when working on the main branch in `jmpost` - that is at least where I saw it, hope it is reproducible on your side.

**Comment by dgkf** [comment]
Was resolved in #10
